#!/bin/tcsh

#PBS -l walltime=30:00:00,nodes=1:ppn=2:gpu -q home-gibbs -A mgilson-gpu
#PBS -j oe -r n -m n 
#PBS -N STAGE-POSE

### Set Environment
module swap intel gnu
module load python
module load scipy/2.7
setenv PATH "/home/henrikse/gnu44-bin:/opt/mvapich2/gnu/ib/bin:$PATH"
setenv CUDA_HOME "/opt/cuda/7.5.18"
setenv LD_LIBRARY_PATH "${CUDA_HOME}/lib64:/opt/mvapich2/gnu/ib/lib:$LD_LIBRARY_PATH"
source /home/gheinzel/amber20.csh

### Copy input files to scratch folder
cd $PBS_O_WORKDIR

### Execute
$AMBERHOME/bin/pmemd.cuda -O -i mdin-01 -p full.hmr.prmtop -c md00.rst7 -o md-01.out -r md01.rst7 -x md01.nc -ref full.inpcrd
sleep 10
$AMBERHOME/bin/pmemd.cuda -O -i mdin-02 -p full.hmr.prmtop -c md01.rst7 -o md-02.out -r md02.rst7 -x md02.nc -ref full.inpcrd

### Copy back to Original Work Dir.

