#!/bin/tcsh

#PBS -l walltime=2:00:00,nodes=1:ppn=4 -q home-gibbs -A mgilson-gpu
#PBS -j oe -r n -m n 
#PBS -N Create_system

### Set Environment
source /home/gheinzel/amber20/amber-new.csh

### Execute
cd $PBS_O_WORKDIR
/home/gheinzel/amber20/miniconda/bin/python BAT.py -i input.in -s analysis

