#!/bin/bash

#SBATCH --job-name="STAGE-POSE"
#SBATCH --partition=rondror
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH -t 12:00:00

# Main command goes here
source $GROUP_HOME/software/amber20/amber20_src/setup_amber.sh
source run-local.bash

exit