#!/bin/bash

#SBATCH --job-name="STAGE-POSE"
#SBATCH --partition=rondror
#SBATCH --nodes=1
#SBATCH --output=STAGE-POSE.out
#SBATCH --error=STAGE-POSE.err
#SBATCH --gres=gpu:1
#SBATCH --gpu_cmode=shared
#SBATCH --ntasks=1
#SBATCH -t 12:00:00

scontrol show job $SLURM_JOB_ID
source run-local.bash

exit